SC-3111: Handover of Benchmark Performance Audit Tool in Cloud
spryker-sdk/benchmark pull request #2
Opened 2020-08-31 07:31 UTC by zyuzka

Ticket: https://spryker.atlassian.net/browse/SC-3111

2020-09-02 07:42 UTC, AsonUnique commented on src/SprykerSdk/Glue/Benchmark/Command/CommandBuilder.php
> +    protected $config;
```suggestion
    protected $benchmarkConfig;
```

2020-09-02 07:42 UTC, AsonUnique commented on src/SprykerSdk/Glue/Benchmark/Command/CommandBuilder.php
> +    protected function getDefaultTestsDirectory(): string
I guess you can omit `Default` here (or substitute it with `Application`).

2020-09-02 07:42 UTC, AsonUnique commented on src/SprykerSdk/Glue/Benchmark/Plugin/Console/BenchmarkRunConsole.php
> +            ->addOption('report', null, InputOption::VALUE_OPTIONAL, 'Path to the directory that contains tests to be executed')
Please, fix the description of options.

2020-09-02 07:42 UTC, AsonUnique commented on src/SprykerSdk/Shared/Benchmark/BenchmarkConfig.php
> +        return 'generator: "table", cols:["benchmark", "subject", "best", "mean", "worst", "stdev", "revs", "its"]';
Usually, default values extracted to class constants.

2020-09-02 07:42 UTC, AsonUnique commented on src/SprykerSdk/Shared/Benchmark/Command/AbstractCommandBuilder.php
> +        $commandTemplate = self::BASED_PHPBENCH_COMMAND;
```suggestion
        $commandTemplate = static::BASED_PHPBENCH_COMMAND;
```

2020-09-02 07:42 UTC, AsonUnique commented on src/SprykerSdk/Shared/Benchmark/Command/AbstractCommandBuilder.php
> +        $moduleRootFolder = __DIR__ . '/../../../../../..';
```suggestion
        $moduleRootFolder = dirname(__DIR__,  6);
```

2020-09-02 07:42 UTC, AsonUnique commented on src/SprykerSdk/Shared/Benchmark/Command/AbstractCommandBuilder.php
> +        return '--bootstrap=' . $bootstrapPath;
please, consider moving these options to a class constants.

2020-09-02 07:42 UTC, AsonUnique commented on src/SprykerSdk/Glue/Benchmark/Command/CommandBuilder.php
> +    protected $config;
Please, check Yves and Zed layers too.

2020-09-02 07:42 UTC, AsonUnique commented on src/SprykerSdk/Glue/Benchmark/Command/CommandBuilder.php
> +    protected function getDefaultTestsDirectory(): string
Please, check Yves and Zed layers too.

2020-09-02 07:42 UTC, AsonUnique commented on src/SprykerSdk/Yves/Benchmark/Plugin/Console/BenchmarkRunConsole.php
> +            ->addOption('path', null, InputOption::VALUE_OPTIONAL, 'Path to the directory that contains tests to be executed')
Please, fix descriptions.

2020-09-02 07:42 UTC, AsonUnique commented on src/SprykerSdk/Zed/Benchmark/Communication/Console/BenchmarkRunConsole.php
> +            ->addOption('path', null, InputOption::VALUE_OPTIONAL, 'Path to the directory that contains tests to be executed')
Also here

2020-09-09 18:27 UTC, alexanderM91 requested changes

2020-09-09 18:27 UTC, alexanderM91 commented on src/SprykerSdk/Shared/Benchmark/BenchmarkConfig.php
> +     * @api
Please add specification

2020-09-09 18:27 UTC, alexanderM91 commented on src/SprykerSdk/Shared/Benchmark/BenchmarkConfig.php
> +     * @api
Please add specification

2020-09-09 18:27 UTC, alexanderM91 commented on src/SprykerSdk/Shared/Benchmark/BenchmarkConfig.php
> +     * @api
Please add specification.

2020-09-09 18:27 UTC, alexanderM91 commented on src/SprykerSdk/Shared/Benchmark/BenchmarkConfig.php
> +        return 1;
Maybe it's better to move it to const

2020-09-09 18:27 UTC, alexanderM91 commented on src/SprykerSdk/Glue/Benchmark/Command/CommandBuilder.php
> +        $this->config = $config;
Please rename `$config` to `$benchmarkConfig`

2020-09-09 18:27 UTC, alexanderM91 commented on src/SprykerSdk/Yves/Benchmark/Command/CommandBuilder.php
> +    public function __construct(BenchmarkConfig $config)
Please rename `$config` to `$benchmarkConfig`

2020-09-09 18:27 UTC, alexanderM91 commented on src/SprykerSdk/Yves/Benchmark/Command/CommandBuilder.php
> +    protected function getIterationConfig(): int
Maybe it's better to omit `..Config()`, e.g
It could be `getIteration()`?

2020-09-09 18:27 UTC, alexanderM91 commented on src/SprykerSdk/Yves/Benchmark/Command/CommandBuilder.php
> +    protected function getIterationConfig(): int
Is it an application-specific configuration?

2020-09-09 18:27 UTC, alexanderM91 commented on src/SprykerSdk/Shared/Benchmark/Command/AbstractCommandBuilder.php
> +    abstract protected function getIterationConfig(): int;
IMO it doesn't make sense for these abstract methods per each application layer.
If I got it correctly we can set the default value inside the console command for Yves, Zed, and Glue.

2020-09-11 08:43 UTC, alexanderM91 commented on src/SprykerSdk/Shared/Benchmark/BenchmarkConfig.php
> +        return static::BENCHMARK_REPORT_CONFIG;
An exception will be here

2020-09-15 09:19 UTC, alexanderM91 commented
Covered by https://github.com/spryker-sdk/benchmark/pull/3

2020-09-15 09:19 UTC, closed without merging